-- 0084 — drop "one order per RFQ" (orders_rfq_uq), keep "one order line per RFQ item".
--
-- Partial confirmation (the legacy cart, 0083 port) makes an order "what was confirmed together":
-- batch 1 confirms three of four lines, batch 2 the fourth — two orders, one RFQ, by design.
-- The once-only rule that actually protects money lives at the LINE level and stays DB-enforced:
-- order_items.rfq_item_id is still unique. A plain index replaces the unique so the FK joins keep
-- their plan. Generated by drizzle-kit from the schema edit, so snapshot and DB stay in step.

DROP INDEX IF EXISTS "orders_rfq_uq";--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "orders_rfq_idx" ON "orders" USING btree ("rfq_id");